import { Panel } from "@/components/widgets/Panel";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Brain, ChevronRight, Play, Sparkles, Zap } from "lucide-react";
import { aiHypotheses, generateTimeSeries } from "@/data/mock";
import { AreaChartWidget, MiniArea } from "@/components/widgets/Charts";
import { LogStream } from "@/components/widgets/LogStream";
import { Progress } from "@/components/ui/progress";

export default function RCA() {
  const data = generateTimeSeries(30, 100, 40);
  return (
    <div className="p-6 space-y-6 animate-fade-in">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <div className="text-xs text-muted-foreground mb-1">Operations / AI RCA</div>
          <h1 className="text-3xl font-bold tracking-tight flex items-center gap-3">
            <Brain className="h-8 w-8 text-primary" /> AI Root Cause Analyzer
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Synthesising signals across logs, metrics & traces · Model: WebPulse-RCA-v4
          </p>
        </div>
        <Button className="bg-gradient-primary"><Sparkles className="h-4 w-4 mr-2" /> Re-run Analysis</Button>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {[
          { t: "Logs Analysed", v: "2.4M", d: "Last 30 min · 12 services" },
          { t: "Metrics Series", v: "847", d: "1s resolution · 4h window" },
          { t: "Traces Sampled", v: "184k", d: "Including 12k errors" },
        ].map((s) => (
          <div key={s.t} className="rounded-xl border border-border bg-card p-5">
            <div className="text-xs uppercase tracking-wider text-muted-foreground">{s.t}</div>
            <div className="text-3xl font-bold gradient-text mt-1">{s.v}</div>
            <div className="text-xs text-muted-foreground mt-1">{s.d}</div>
            <MiniArea data={data} height={32} color="hsl(var(--primary))" />
          </div>
        ))}
      </div>

      {/* Confidence score panel */}
      <div className="rounded-2xl border border-primary/30 bg-gradient-glow p-6 shadow-elegant">
        <div className="flex flex-wrap items-center justify-between gap-6">
          <div>
            <Badge className="bg-gradient-primary text-primary-foreground mb-2">PRIMARY HYPOTHESIS</Badge>
            <h2 className="text-2xl font-bold">Database connection pool exhaustion</h2>
            <p className="text-sm text-muted-foreground mt-1">
              order-service v4.2.1 · deployed 14:28 UTC · introduced unintended connection retention in OrderRepository
            </p>
          </div>
          <div className="text-center">
            <div className="text-5xl font-bold gradient-text">94<span className="text-2xl">%</span></div>
            <div className="text-xs uppercase tracking-wider text-muted-foreground mt-1">AI Confidence</div>
            <Progress value={94} className="mt-2 h-1.5 w-32" />
          </div>
        </div>
      </div>

      {/* Hypotheses */}
      <Panel title="Ranked Hypotheses" subtitle="Generated by AI synthesis engine">
        <div className="space-y-3">
          {aiHypotheses.map((h) => (
            <div key={h.rank} className={`rounded-xl border p-4 ${h.rank === 1 ? "border-primary/40 bg-primary/5" : "border-border"}`}>
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-start gap-3 min-w-0">
                  <div className={`h-8 w-8 rounded-lg grid place-items-center text-sm font-bold shrink-0 ${
                    h.rank === 1 ? "bg-gradient-primary text-primary-foreground" : "bg-muted"
                  }`}>
                    #{h.rank}
                  </div>
                  <div>
                    <div className="font-semibold">{h.title}</div>
                    <div className="text-sm text-muted-foreground mt-2">{h.suggestedFix}</div>
                    <div className="mt-3 grid grid-cols-1 md:grid-cols-2 gap-1.5">
                      {h.evidence.map((e, i) => (
                        <div key={i} className="flex items-start gap-1.5 text-xs text-muted-foreground">
                          <ChevronRight className="h-3 w-3 mt-0.5 text-primary shrink-0" />
                          <span>{e}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
                <div className="text-right shrink-0">
                  <div className="text-2xl font-bold gradient-text">{h.confidence}%</div>
                  <Progress value={h.confidence} className="h-1 w-20 mt-2" />
                </div>
              </div>
              <div className="mt-3 flex gap-2">
                <Button size="sm" variant={h.rank === 1 ? "default" : "outline"} className={h.rank === 1 ? "bg-gradient-primary" : ""}>
                  <Zap className="h-3.5 w-3.5 mr-1.5" /> Apply Fix
                </Button>
                <Button size="sm" variant="outline">
                  <Play className="h-3.5 w-3.5 mr-1.5" /> Simulate
                </Button>
              </div>
            </div>
          ))}
        </div>
      </Panel>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Panel title="Metric Anomalies" className="lg:col-span-2">
          <AreaChartWidget data={data} height={240} />
        </Panel>
        <Panel title="Recovery Simulation">
          <div className="space-y-3 text-sm">
            <div className="flex justify-between"><span>Apply pool scaling</span><span className="text-success">~30s</span></div>
            <div className="flex justify-between"><span>Drain stale connections</span><span className="text-success">~45s</span></div>
            <div className="flex justify-between"><span>Verify error rate normalised</span><span className="text-success">~2m</span></div>
            <div className="flex justify-between font-semibold pt-2 border-t border-border"><span>Estimated recovery</span><span className="gradient-text">3m 15s</span></div>
            <Button className="w-full bg-gradient-primary mt-2"><Zap className="h-4 w-4 mr-2" /> Execute Plan</Button>
          </div>
        </Panel>
      </div>

      <Panel title="Log Evidence" subtitle="Signals supporting top hypothesis">
        <LogStream />
      </Panel>
    </div>
  );
}
